---
# tasks file for nginx
  - name: Install Nginx
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ package }}"

  - name: Start The Nginx
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - "{{ package }}"

  - name: copy the index.html file into webserver
    ansible.builtin.copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Changing the port number
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: Restart nginx
